<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kontak extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kontak_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        if(isset($_SESSION['username'])){
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'admin/kontak/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'admin/kontak/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'admin/kontak/index.html';
            $config['first_url'] = base_url() . 'admin/kontak/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Kontak_model->total_rows($q);
        $kontak = $this->Kontak_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'kontak_data' => $kontak,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            "container" => "admin/kontak/kontak_list", 
            "footer" => "admin/footer", 
            "nav" => "admin/nav"
        );
        $this->load->view('admin/template', $data);
        } else {
            redirect(base_url("admin/index"));
        }
    }

    public function update($id) 
    {
        $row = $this->Kontak_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kontak/update_action'),
                'id_kontak' => set_value('id_kontak', $row->id_kontak),
                'alamat_kontak' => set_value('alamat_kontak', $row->alamat_kontak),
                'email_kontak' => set_value('email_kontak', $row->email_kontak),
                'telepon_kontak' => set_value('telepon_kontak', $row->telepon_kontak),
                "container" => "admin/kontak/kontak_form", 
                "footer" => "admin/footer",
                "nav" => "admin/nav"
	    );
            $this->load->view('admin/template', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kontak'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kontak', TRUE));
        } else {
            $data = array(
		'alamat_kontak' => $this->input->post('alamat_kontak',TRUE),
		'email_kontak' => $this->input->post('email_kontak',TRUE),
		'telepon_kontak' => $this->input->post('telepon_kontak',TRUE),
	    );

            $this->Kontak_model->update($this->input->post('id_kontak', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/kontak'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('alamat_kontak', 'alamat kontak', 'trim|required');
	$this->form_validation->set_rules('email_kontak', 'email kontak', 'trim|required');
	$this->form_validation->set_rules('telepon_kontak', 'telepon kontak', 'trim|required');

	$this->form_validation->set_rules('id_kontak', 'id_kontak', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kontak.php */
/* Location: ./application/controllers/Kontak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-24 08:17:26 */
/* http://harviacode.com */