<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sewa_jasa_model extends CI_Model
{

    public $table = 'sewa_jasa';
    public $id = 'id_sj';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sj', $q);
	$this->db->or_like('id_jasa', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('biaya', $q);
	$this->db->or_like('tgl_sewa', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tgl_acara', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data1($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sj', $q);
	$this->db->or_like('id_jasa', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('biaya', $q);
	$this->db->or_like('tgl_sewa', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tgl_acara', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
     function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sj', $q);
        $this->db->or_like('sewa_jasa.id_jasa', $q);
        $this->db->or_like('sewa_jasa.id_user', $q);
        $this->db->or_like('sewa_jasa.biaya', $q);
        $this->db->or_like('sewa_jasa.tgl_sewa', $q);
        $this->db->or_like('sewa_jasa.alamat', $q);
        $this->db->or_like('sewa_jasa.tgl_acara', $q);
        $this->db->or_like('user.nama_user', $q);
        $this->db->or_like('jasa.nama', $q);
        $this->db->or_like('sewa_jasa.id_sj', $q);
        $this->db->limit($limit, $start);
        $this->db->select('*');
        $this->db->from('sewa_jasa');
        $this->db->join('pembayaran', 'sewa_jasa.id_sj = pembayaran.id_sewa');
        $this->db->join('jasa', 'sewa_jasa.id_jasa = jasa.id_jasa');
        $this->db->join('user', 'sewa_jasa.id_user = user.id_user');
        $query = $this->db->get();
        return  $query->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sewa_jasa_model.php */
/* Location: ./application/models/Sewa_jasa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-26 17:05:49 */
/* http://harviacode.com */